---
- ansible.builtin.include_tasks: ../../_lab_common/tasks/gitlab.yml
  vars: { lab_enabled: "{{ gitlab_source_exposure_enabled }}", lab_gitlab_url: "{{ gitlab_source_exposure_url }}", lab_gitlab_token: "{{ gitlab_source_exposure_token }}", lab_gitlab_project: "{{ gitlab_source_exposure_project }}", lab_gitlab_settings: { visibility: "{{ gitlab_source_exposure_visibility }}" } }
