---
- ansible.builtin.include_tasks: ../../_lab_common/tasks/windows.yml
  vars: { lab_enabled: "{{ windows_smb_insecure_guest_auth_enabled }}", lab_target_profile: "{{ windows_smb_insecure_guest_auth_target_profile }}", lab_action: smb_guest, lab_target: localhost, lab_required_feature: '', lab_required_service: LanmanWorkstation, lab_principal: '', lab_value: '', lab_path: '', lab_windows_features: [], lab_no_log: false }
